---
minimum_pre_commit_version: 2.9.0
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: check-ast
  - id: check-toml
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: detect-private-key
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: name-tests-test
    args:
    - --pytest-test-first
  - id: sort-simple-yaml
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '100']
    exclude: robo.yml
