title: phvv.me
description: Pedro Valois' personal website. Bookmark to keep an eye on my project updates!

# https://github.com/pages-themes/minimal
theme: jekyll-theme-minimal
logo: /assets/icon/icon-dark.svg
show_downloads: false
# TODO: google_analytics: 

# reference: https://jekyllrb.com/docs/configuration/options/
source: .
safe: true
incremental: false
highlighter: rouge

# https://jekyll.github.io/classifier-reborn/lsi
lsi: true

# gist:
#   noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


